# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interfaz2(object):
    def setupUi(self, Interfaz2):
        Interfaz2.setObjectName("Interfaz2")
        Interfaz2.resize(1366, 768)
        Interfaz2.setMinimumSize(QtCore.QSize(1366, 768))
        Interfaz2.setMaximumSize(QtCore.QSize(1366, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../DURAPROFIT INVI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Interfaz2.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Interfaz2)
        self.centralwidget.setMinimumSize(QtCore.QSize(1366, 768))
        self.centralwidget.setMaximumSize(QtCore.QSize(1366, 768))
        self.centralwidget.setObjectName("centralwidget")
        self.DATOS = QtWidgets.QTabWidget(self.centralwidget)
        self.DATOS.setGeometry(QtCore.QRect(0, 0, 1831, 881))
        self.DATOS.setMinimumSize(QtCore.QSize(0, 881))
        self.DATOS.setStyleSheet("background-color:rgb(5, 51, 74);")
        self.DATOS.setTabPosition(QtWidgets.QTabWidget.North)
        self.DATOS.setObjectName("DATOS")
        self.Datos = QtWidgets.QWidget()
        self.Datos.setObjectName("Datos")
        self.groupBox = QtWidgets.QGroupBox(self.Datos)
        self.groupBox.setGeometry(QtCore.QRect(380, 210, 181, 251))
        self.groupBox.setStyleSheet("color: white;\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background: none;\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.Extraer = QtWidgets.QPushButton(self.groupBox)
        self.Extraer.setGeometry(QtCore.QRect(20, 30, 141, 61))
        self.Extraer.setMouseTracking(False)
        self.Extraer.setStyleSheet("background:rgb(47, 168, 170); color:white;\n"
"font: 10pt \"MS Shell Dlg 2\"; border-radius: 15;")
        self.Extraer.setObjectName("Extraer")
        self.Cerrar = QtWidgets.QPushButton(self.groupBox)
        self.Cerrar.setGeometry(QtCore.QRect(20, 170, 141, 61))
        self.Cerrar.setMouseTracking(False)
        self.Cerrar.setStyleSheet("background:rgb(47, 168, 170); color:white;\n"
"font: 10pt \"MS Shell Dlg 2\"; border-radius: 15;")
        self.Cerrar.setObjectName("Cerrar")
        self.Limpiar = QtWidgets.QPushButton(self.groupBox)
        self.Limpiar.setGeometry(QtCore.QRect(20, 100, 141, 61))
        self.Limpiar.setMouseTracking(False)
        self.Limpiar.setStyleSheet("background:rgb(47, 168, 170); color:white;\n"
"font: 10pt \"MS Shell Dlg 2\"; border-radius: 15;")
        self.Limpiar.setObjectName("Limpiar")
        self.label = QtWidgets.QLabel(self.Datos)
        self.label.setGeometry(QtCore.QRect(200, 30, 931, 71))
        self.label.setStyleSheet("background: none; font: 36pt \"MS Shell Dlg 2\";color: white;")
        self.label.setObjectName("label")
        self.CuadroDatos = QtWidgets.QTextEdit(self.Datos)
        self.CuadroDatos.setGeometry(QtCore.QRect(610, 130, 451, 491))
        self.CuadroDatos.setStyleSheet("background-color: rgb(5, 51, 74);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"border-color: rgb(5, 51, 74);\n"
"")
        self.CuadroDatos.setObjectName("CuadroDatos")
        self.DATOS.addTab(self.Datos, "")
        self.Costo = QtWidgets.QWidget()
        self.Costo.setEnabled(True)
        self.Costo.setObjectName("Costo")
        self.label_2 = QtWidgets.QLabel(self.Costo)
        self.label_2.setGeometry(QtCore.QRect(170, 290, 231, 41))
        self.label_2.setStyleSheet("background: none; color: white;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.EditCostoEnergia = QtWidgets.QLineEdit(self.Costo)
        self.EditCostoEnergia.setGeometry(QtCore.QRect(410, 290, 281, 41))
        self.EditCostoEnergia.setStyleSheet("background-color: rgb(5, 51, 74);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"border-color: rgb(5, 51, 74);\n"
"\n"
"")
        self.EditCostoEnergia.setObjectName("EditCostoEnergia")
        self.label_4 = QtWidgets.QLabel(self.Costo)
        self.label_4.setGeometry(QtCore.QRect(170, 240, 231, 41))
        self.label_4.setStyleSheet("background: none; \n"
"color: white;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.EditInversion = QtWidgets.QLineEdit(self.Costo)
        self.EditInversion.setGeometry(QtCore.QRect(410, 240, 281, 41))
        self.EditInversion.setStyleSheet("background-color: rgb(5, 51, 74);\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"border-color: rgb(5, 51, 74);\n"
"")
        self.EditInversion.setObjectName("EditInversion")
        self.CalcularTiempo = QtWidgets.QPushButton(self.Costo)
        self.CalcularTiempo.setGeometry(QtCore.QRect(370, 360, 181, 61))
        self.CalcularTiempo.setMouseTracking(False)
        self.CalcularTiempo.setStyleSheet("background:rgb(47, 168, 170); color:white;\n"
"font: 10pt \"MS Shell Dlg 2\"; border-radius: 15;")
        self.CalcularTiempo.setObjectName("CalcularTiempo")
        self.CuadroCostos = QtWidgets.QLabel(self.Costo)
        self.CuadroCostos.setGeometry(QtCore.QRect(710, 230, 551, 201))
        self.CuadroCostos.setStyleSheet("background: none;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CuadroCostos.setText("")
        self.CuadroCostos.setObjectName("CuadroCostos")
        self.Titulo1 = QtWidgets.QLabel(self.Costo)
        self.Titulo1.setGeometry(QtCore.QRect(770, 100, 621, 51))
        self.Titulo1.setStyleSheet("background: none;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.Titulo1.setObjectName("Titulo1")
        self.Titulo1_2 = QtWidgets.QLabel(self.Costo)
        self.Titulo1_2.setGeometry(QtCore.QRect(770, 150, 621, 51))
        self.Titulo1_2.setStyleSheet("background: none;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.Titulo1_2.setObjectName("Titulo1_2")
        self.PrecioBTC = QtWidgets.QLabel(self.Costo)
        self.PrecioBTC.setGeometry(QtCore.QRect(120, 510, 201, 51))
        self.PrecioBTC.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioBTC.setObjectName("PrecioBTC")
        self.PrecioETH = QtWidgets.QLabel(self.Costo)
        self.PrecioETH.setGeometry(QtCore.QRect(460, 510, 231, 51))
        self.PrecioETH.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioETH.setObjectName("PrecioETH")
        self.PrecioZEC = QtWidgets.QLabel(self.Costo)
        self.PrecioZEC.setGeometry(QtCore.QRect(790, 510, 171, 51))
        self.PrecioZEC.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioZEC.setObjectName("PrecioZEC")
        self.PrecioXMR = QtWidgets.QLabel(self.Costo)
        self.PrecioXMR.setGeometry(QtCore.QRect(1090, 510, 221, 51))
        self.PrecioXMR.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioXMR.setObjectName("PrecioXMR")
        self.PrecioETC = QtWidgets.QLabel(self.Costo)
        self.PrecioETC.setGeometry(QtCore.QRect(260, 610, 311, 51))
        self.PrecioETC.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioETC.setObjectName("PrecioETC")
        self.PrecioDASH = QtWidgets.QLabel(self.Costo)
        self.PrecioDASH.setGeometry(QtCore.QRect(610, 610, 151, 51))
        self.PrecioDASH.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioDASH.setObjectName("PrecioDASH")
        self.PrecioLTC = QtWidgets.QLabel(self.Costo)
        self.PrecioLTC.setGeometry(QtCore.QRect(920, 610, 211, 51))
        self.PrecioLTC.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioLTC.setObjectName("PrecioLTC")
        self.PrecioBTCimg = QtWidgets.QLabel(self.Costo)
        self.PrecioBTCimg.setGeometry(QtCore.QRect(70, 520, 41, 41))
        self.PrecioBTCimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioBTCimg.setText("")
        self.PrecioBTCimg.setScaledContents(True)
        self.PrecioBTCimg.setObjectName("PrecioBTCimg")
        self.PrecioETHimg = QtWidgets.QLabel(self.Costo)
        self.PrecioETHimg.setGeometry(QtCore.QRect(400, 520, 41, 41))
        self.PrecioETHimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioETHimg.setText("")
        self.PrecioETHimg.setScaledContents(True)
        self.PrecioETHimg.setObjectName("PrecioETHimg")
        self.PrecioZECimg = QtWidgets.QLabel(self.Costo)
        self.PrecioZECimg.setGeometry(QtCore.QRect(740, 510, 41, 41))
        self.PrecioZECimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioZECimg.setText("")
        self.PrecioZECimg.setScaledContents(True)
        self.PrecioZECimg.setObjectName("PrecioZECimg")
        self.PrecioXMRimg = QtWidgets.QLabel(self.Costo)
        self.PrecioXMRimg.setGeometry(QtCore.QRect(1040, 520, 41, 41))
        self.PrecioXMRimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioXMRimg.setText("")
        self.PrecioXMRimg.setScaledContents(True)
        self.PrecioXMRimg.setObjectName("PrecioXMRimg")
        self.PrecioETCimg = QtWidgets.QLabel(self.Costo)
        self.PrecioETCimg.setGeometry(QtCore.QRect(200, 620, 41, 41))
        self.PrecioETCimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioETCimg.setText("")
        self.PrecioETCimg.setScaledContents(True)
        self.PrecioETCimg.setObjectName("PrecioETCimg")
        self.PrecioDASHimg = QtWidgets.QLabel(self.Costo)
        self.PrecioDASHimg.setGeometry(QtCore.QRect(560, 620, 41, 41))
        self.PrecioDASHimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioDASHimg.setText("")
        self.PrecioDASHimg.setScaledContents(True)
        self.PrecioDASHimg.setObjectName("PrecioDASHimg")
        self.PrecioLTCimg = QtWidgets.QLabel(self.Costo)
        self.PrecioLTCimg.setGeometry(QtCore.QRect(870, 620, 41, 41))
        self.PrecioLTCimg.setStyleSheet("background: none;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.PrecioLTCimg.setText("")
        self.PrecioLTCimg.setScaledContents(True)
        self.PrecioLTCimg.setObjectName("PrecioLTCimg")
        self.Warning1 = QtWidgets.QLabel(self.Costo)
        self.Warning1.setGeometry(QtCore.QRect(20, 20, 1341, 51))
        self.Warning1.setStyleSheet("background: none;\n"
"font: 19.5pt \"MS Shell Dlg 2\";\n"
"color: RED;\n"
"")
        self.Warning1.setObjectName("Warning1")
        self.TituloMain = QtWidgets.QLabel(self.Costo)
        self.TituloMain.setGeometry(QtCore.QRect(550, 20, 321, 51))
        self.TituloMain.setStyleSheet("background: none;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.TituloMain.setObjectName("TituloMain")
        self.label_5 = QtWidgets.QLabel(self.Costo)
        self.label_5.setGeometry(QtCore.QRect(470, 700, 761, 31))
        self.label_5.setStyleSheet("background: none;\n"
"font: 10\n"
"pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.label_5.setObjectName("label_5")
        self.DATOS.addTab(self.Costo, "")
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Info)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 1301, 601))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.MainInfo = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MainInfo.setContentsMargins(0, 0, 0, 0)
        self.MainInfo.setObjectName("MainInfo")
        self.Modelos = QtWidgets.QVBoxLayout()
        self.Modelos.setObjectName("Modelos")
        self.Modelo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Modelo.setStyleSheet("background: none;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.Modelo.setText("")
        self.Modelo.setObjectName("Modelo")
        self.Modelos.addWidget(self.Modelo)
        self.GPURank1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank1.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank1.setText("")
        self.GPURank1.setObjectName("GPURank1")
        self.Modelos.addWidget(self.GPURank1)
        self.GPURank2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank2.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank2.setText("")
        self.GPURank2.setObjectName("GPURank2")
        self.Modelos.addWidget(self.GPURank2)
        self.GPURank3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank3.setStyleSheet("background: none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.GPURank3.setText("")
        self.GPURank3.setObjectName("GPURank3")
        self.Modelos.addWidget(self.GPURank3)
        self.GPURank4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank4.setStyleSheet("background: none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank4.setText("")
        self.GPURank4.setObjectName("GPURank4")
        self.Modelos.addWidget(self.GPURank4)
        self.GPURank5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank5.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank5.setText("")
        self.GPURank5.setObjectName("GPURank5")
        self.Modelos.addWidget(self.GPURank5)
        self.GPURank6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank6.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank6.setText("")
        self.GPURank6.setObjectName("GPURank6")
        self.Modelos.addWidget(self.GPURank6)
        self.GPURank7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank7.setStyleSheet("background: none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank7.setText("")
        self.GPURank7.setObjectName("GPURank7")
        self.Modelos.addWidget(self.GPURank7)
        self.GPURank8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank8.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank8.setText("")
        self.GPURank8.setObjectName("GPURank8")
        self.Modelos.addWidget(self.GPURank8)
        self.GPURank9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank9.setStyleSheet("background: none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank9.setText("")
        self.GPURank9.setObjectName("GPURank9")
        self.Modelos.addWidget(self.GPURank9)
        self.GPURank10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.GPURank10.setStyleSheet("background: none;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.GPURank10.setText("")
        self.GPURank10.setObjectName("GPURank10")
        self.Modelos.addWidget(self.GPURank10)
        self.MainInfo.addLayout(self.Modelos)
        self.FechasdeSalida = QtWidgets.QVBoxLayout()
        self.FechasdeSalida.setObjectName("FechasdeSalida")
        self.FechaSalida = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaSalida.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaSalida.setText("")
        self.FechaSalida.setObjectName("FechaSalida")
        self.FechasdeSalida.addWidget(self.FechaSalida)
        self.FechaRank1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank1.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank1.setText("")
        self.FechaRank1.setObjectName("FechaRank1")
        self.FechasdeSalida.addWidget(self.FechaRank1)
        self.FechaRank2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank2.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank2.setText("")
        self.FechaRank2.setObjectName("FechaRank2")
        self.FechasdeSalida.addWidget(self.FechaRank2)
        self.FechaRank3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank3.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank3.setText("")
        self.FechaRank3.setObjectName("FechaRank3")
        self.FechasdeSalida.addWidget(self.FechaRank3)
        self.FechaRank4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank4.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank4.setText("")
        self.FechaRank4.setObjectName("FechaRank4")
        self.FechasdeSalida.addWidget(self.FechaRank4)
        self.FechaRank5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank5.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank5.setText("")
        self.FechaRank5.setObjectName("FechaRank5")
        self.FechasdeSalida.addWidget(self.FechaRank5)
        self.FechaRank6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank6.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank6.setText("")
        self.FechaRank6.setObjectName("FechaRank6")
        self.FechasdeSalida.addWidget(self.FechaRank6)
        self.FechaRank7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank7.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank7.setText("")
        self.FechaRank7.setObjectName("FechaRank7")
        self.FechasdeSalida.addWidget(self.FechaRank7)
        self.FechaRank8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank8.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank8.setText("")
        self.FechaRank8.setObjectName("FechaRank8")
        self.FechasdeSalida.addWidget(self.FechaRank8)
        self.FechaRank9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank9.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank9.setText("")
        self.FechaRank9.setObjectName("FechaRank9")
        self.FechasdeSalida.addWidget(self.FechaRank9)
        self.FechaRank10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.FechaRank10.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.FechaRank10.setText("")
        self.FechaRank10.setObjectName("FechaRank10")
        self.FechasdeSalida.addWidget(self.FechaRank10)
        self.MainInfo.addLayout(self.FechasdeSalida)
        self.Hashrates = QtWidgets.QVBoxLayout()
        self.Hashrates.setObjectName("Hashrates")
        self.Hashrate = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Hashrate.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.Hashrate.setText("")
        self.Hashrate.setObjectName("Hashrate")
        self.Hashrates.addWidget(self.Hashrate)
        self.HRank1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank1.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank1.setText("")
        self.HRank1.setObjectName("HRank1")
        self.Hashrates.addWidget(self.HRank1)
        self.HRank2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank2.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank2.setText("")
        self.HRank2.setObjectName("HRank2")
        self.Hashrates.addWidget(self.HRank2)
        self.HRank3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank3.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank3.setText("")
        self.HRank3.setObjectName("HRank3")
        self.Hashrates.addWidget(self.HRank3)
        self.HRank4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank4.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank4.setText("")
        self.HRank4.setObjectName("HRank4")
        self.Hashrates.addWidget(self.HRank4)
        self.HRank5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank5.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank5.setText("")
        self.HRank5.setObjectName("HRank5")
        self.Hashrates.addWidget(self.HRank5)
        self.HRank6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank6.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank6.setText("")
        self.HRank6.setObjectName("HRank6")
        self.Hashrates.addWidget(self.HRank6)
        self.HRank7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank7.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank7.setText("")
        self.HRank7.setObjectName("HRank7")
        self.Hashrates.addWidget(self.HRank7)
        self.HRank8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank8.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank8.setText("")
        self.HRank8.setObjectName("HRank8")
        self.Hashrates.addWidget(self.HRank8)
        self.HRank9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank9.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank9.setText("")
        self.HRank9.setObjectName("HRank9")
        self.Hashrates.addWidget(self.HRank9)
        self.HRank10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.HRank10.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.HRank10.setText("")
        self.HRank10.setObjectName("HRank10")
        self.Hashrates.addWidget(self.HRank10)
        self.MainInfo.addLayout(self.Hashrates)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CE = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CE.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CE.setText("")
        self.CE.setObjectName("CE")
        self.verticalLayout.addWidget(self.CE)
        self.CERank1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank1.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank1.setText("")
        self.CERank1.setObjectName("CERank1")
        self.verticalLayout.addWidget(self.CERank1)
        self.CERank2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank2.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank2.setText("")
        self.CERank2.setObjectName("CERank2")
        self.verticalLayout.addWidget(self.CERank2)
        self.CERank3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank3.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank3.setText("")
        self.CERank3.setObjectName("CERank3")
        self.verticalLayout.addWidget(self.CERank3)
        self.CERank4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank4.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank4.setText("")
        self.CERank4.setObjectName("CERank4")
        self.verticalLayout.addWidget(self.CERank4)
        self.CERank5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank5.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank5.setText("")
        self.CERank5.setObjectName("CERank5")
        self.verticalLayout.addWidget(self.CERank5)
        self.CERank6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank6.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank6.setText("")
        self.CERank6.setObjectName("CERank6")
        self.verticalLayout.addWidget(self.CERank6)
        self.CERank7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank7.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank7.setText("")
        self.CERank7.setObjectName("CERank7")
        self.verticalLayout.addWidget(self.CERank7)
        self.CERank8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank8.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank8.setText("")
        self.CERank8.setObjectName("CERank8")
        self.verticalLayout.addWidget(self.CERank8)
        self.CERank9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank9.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank9.setText("")
        self.CERank9.setObjectName("CERank9")
        self.verticalLayout.addWidget(self.CERank9)
        self.CERank10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.CERank10.setStyleSheet("background: none;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.CERank10.setText("")
        self.CERank10.setObjectName("CERank10")
        self.verticalLayout.addWidget(self.CERank10)
        self.MainInfo.addLayout(self.verticalLayout)
        self.label_3 = QtWidgets.QLabel(self.Info)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 1151, 51))
        self.label_3.setStyleSheet("background: none;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.MostrarRaking = QtWidgets.QPushButton(self.Info)
        self.MostrarRaking.setGeometry(QtCore.QRect(400, 250, 601, 151))
        self.MostrarRaking.setMouseTracking(False)
        self.MostrarRaking.setStyleSheet("background:rgb(47, 168, 170);\n"
"color:white;\n"
"font: 25pt \"MS Shell Dlg 2\";\n"
"border-radius: 15;")
        self.MostrarRaking.setObjectName("MostrarRaking")
        self.label_6 = QtWidgets.QLabel(self.Info)
        self.label_6.setGeometry(QtCore.QRect(530, 710, 761, 31))
        self.label_6.setStyleSheet("background: none;\n"
"font: 10\n"
"pt \"MS Shell Dlg 2\";\n"
"color: white;\n"
"")
        self.label_6.setObjectName("label_6")
        self.DATOS.addTab(self.Info, "")
        Interfaz2.setCentralWidget(self.centralwidget)

        self.retranslateUi(Interfaz2)
        self.DATOS.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Interfaz2)

    def retranslateUi(self, Interfaz2):
        _translate = QtCore.QCoreApplication.translate
        Interfaz2.setWindowTitle(_translate("Interfaz2", "DURAPROFIT"))
        self.groupBox.setTitle(_translate("Interfaz2", "COMANDOS"))
        self.Extraer.setText(_translate("Interfaz2", "EXTRAER DATOS"))
        self.Cerrar.setText(_translate("Interfaz2", "CERRAR"))
        self.Limpiar.setText(_translate("Interfaz2", "LIMPIAR"))
        self.label.setText(_translate("Interfaz2", "DATOS GENERADOS DEL MINERO"))
        self.DATOS.setTabText(self.DATOS.indexOf(self.Datos), _translate("Interfaz2", "DATOS"))
        self.label_2.setText(_translate("Interfaz2", "COSTO ENERGÍA EN $/kWh"))
        self.label_4.setText(_translate("Interfaz2", "INVERSIÓN TOTAL EN USD"))
        self.CalcularTiempo.setText(_translate("Interfaz2", "CALCULAR TIEMPO"))
        self.Titulo1.setText(_translate("Interfaz2", "Tiempo necesario"))
        self.Titulo1_2.setText(_translate("Interfaz2", "para recuperar inversión"))
        self.PrecioBTC.setText(_translate("Interfaz2", "BITCOIN"))
        self.PrecioETH.setText(_translate("Interfaz2", "ETHEREUM"))
        self.PrecioZEC.setText(_translate("Interfaz2", "ZCASH"))
        self.PrecioXMR.setText(_translate("Interfaz2", "MONERO"))
        self.PrecioETC.setText(_translate("Interfaz2", "ETHEREUM CLASSIC"))
        self.PrecioDASH.setText(_translate("Interfaz2", "DASH"))
        self.PrecioLTC.setText(_translate("Interfaz2", "LITECOIN"))
        self.Warning1.setText(_translate("Interfaz2", "PROCURA EXTRAER LOS DATOS DE TU COMPUTADORA PRIMERO EN LA PESTAÑA \"DATOS\""))
        self.TituloMain.setText(_translate("Interfaz2", "CALCULADORA"))
        self.label_5.setText(_translate("Interfaz2", "INFORMACIÓN EXTRAIDA DE: https://whattomine.com/coins.json"))
        self.DATOS.setTabText(self.DATOS.indexOf(self.Costo), _translate("Interfaz2", "CALCULADORA"))
        self.label_3.setText(_translate("Interfaz2", "Ranking de mejores GPU para minado de criptomonedas"))
        self.MostrarRaking.setText(_translate("Interfaz2", "MOSTRAR RANKING"))
        self.label_6.setText(_translate("Interfaz2", "INFORMACIÓN EXTRAIDA DE: https://whattomine.com/gpus"))
        self.DATOS.setTabText(self.DATOS.indexOf(self.Info), _translate("Interfaz2", "INFORMACIÓN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interfaz2 = QtWidgets.QMainWindow()
    ui = Ui_Interfaz2()
    ui.setupUi(Interfaz2)
    Interfaz2.show()
    sys.exit(app.exec_())
